# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck_randomizer', '0004_card_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
