# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HS_randomizer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='dbfId',
            field=models.CharField(default='dbfid', max_length=200),
            preserve_default=False,
        ),
    ]
